name: AdhanApp
options:
  bundleIdPrefix: com.adhan
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait"
    INFOPLIST_KEY_UIStatusBarStyle: ""
    INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Adhan needs your location to calculate accurate prayer times for your area."

targets:
  AdhanApp:
    type: application
    platform: iOS
    sources:
      - path: AdhanApp
        excludes:
          - "**/.DS_Store"
        createIntermediateGroups: true
    resources:
      - path: AdhanApp/Assets.xcassets
      - path: AdhanApp/Resources
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.adhan.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_FILE: AdhanApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: AdhanApp/AdhanApp.entitlements
        ENABLE_PREVIEWS: YES
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    info:
      path: AdhanApp/Info.plist
      properties:
        UIBackgroundModes:
          - audio
        NSLocationWhenInUseUsageDescription: "Adhan needs your location to calculate accurate prayer times for your area."
    entitlements:
      path: AdhanApp/AdhanApp.entitlements

schemes:
  AdhanApp:
    build:
      targets:
        AdhanApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
